### ISSUE TITLE
BUG: Not sending CMCD data on manifest request. 

### ISSUE THREAD

**Issue by JoaquinBCh** [montevideo-tech/videojs-cmcd#21]
**What did you expect to happen?**
For all the requests to the CDN that come out of the player to have CMCD data, including all audio/video and initial requests for the index range of a fragment.

**What actually happened?**

When a content is played the initial request asking for the manifest does not contain CMCD data in the URL (as queryparams). This causes the (our validator) app to report an error.

**Comment by coatesjuan** [comment]
This will be fixed with the merge of the branch: https://github.com/montevideo-tech/videojs-cmcd/tree/21-bug-not-sending-cmcd-data-on-manifest-request
